spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fdk_resource
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fdk-resource-service-dev
      auto-offset-reset: earliest

logging:
  level:
    no.fdk.resourceservice: DEBUG
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE







